# TensorFlow Crash Course
# Part 3 Exercises


## 1. Colorize Tim's Garden

In this task, you will first remove the color from this picture:
<img src="task_1/Garden.jpg" alt="Drawing" style="width: 500px;"/>

Thereafter, you will colorize this image by passing it through a convolutional autoencoder. This neural network was trained on the [ImageNet2012 dataset](https://www.tensorflow.org/datasets/catalog/imagenet2012) to colorize gray images.

All files for solving this task are in the folder `task_1`.

### 1.1 Model setup
In the folder `task_1` you can find the `Autoencoder.py` file. It contains the class definition of the `Autoencoder` class. First, create an `Autoencoder` object.
Now you build the model - call the `build` method. Note that, its input shape is `(1, 256, 256, 1)`. In other words, the batch size is `1`. The image has a size of `256x256` pixels and the `1` represents the amount of color channels. There is only one color channel - gray ;).
Thereafter, you will load its trained weights from the `trainied_weights_epoch_12` file.
How many parameters has the model? You can use the `summary` method to get the answer.

### 1.2 Preprocessing
The image `img` is already loaded from the file `Garden.jpg`. It is required that the image has the size of 256x256 pixels. Therefore, you must resize it. In the following, we want to remove the color from the image. You can gray scale an image by taking the average RGB value for each pixel.
The `gray_img` tensor shall have now the shape `(256, 256)`. Due to passing it through convolution layers, a channel dimension is required. 
As a consequence, it must have the shape `(256, 256, 1)`.
Moreover, a batch dimension is expected. Overall, `gray_img` must have the shape `(1, 256, 256, 1)`. Besides, the `autoencoder` expects its input to be in the range of `[-1, 1]`: Normalize the input this way! Before you can do this: Convert the `gray_img` tensor into `float32`.

### 1.3 Inference
Now, you can pass the `gray_img` tensor through the `autoencoder` in order to get `ab_values`.
Next, you must remove the batch dimension. Note that, the `ab_values` are **not** RGB values. For optimization purposes, the `autoencoder` returns A and B values from the [LAB (aka) Color space](https://www.xrite.com/-/media/modules/weblog/blog/lab-color-space/lab-color-space.png?h=622&w=600&la=de&hash=CE9206A0BC3F787A0167DED17D316539ED0C5C08). By concatenating the gray color channels with the A and B color channels (model output), the colorized image is reconstructed. Due to a complex rescaling is applied before the CLAB image is converted into a RGB image, this job is done already for you by the `getRGB` function. Done!

In [3]:
import sys
sys.path.append("./task_1")

import tensorflow as tf
from Autoencoder import Autoencoder
import tensorflow_io as tfio
import matplotlib.pyplot as plt
import cv2

In [6]:
def getRGB(L, AB, batch_mode=True):
    # Remove normalization
    L = (L + 1)*50
    AB = ((AB - 1)*255/2)+128

    if batch_mode:
        L = tf.reshape(L, (32, 256,256,1))
        LAB = tf.concat([L, AB], 3)
    else:
        L = tf.reshape(L, (256,256,1))
        LAB = tf.concat([L, AB], 2)
    rgb = tfio.experimental.color.lab_to_rgb(LAB)

    return rgb

In [7]:
# 1.1 Model setup
# create an autoencoder object

# build the model

# load weights

# Hint: the adam optimizer was used - it's learning rates are not stored 
# -> suppress warnings: use .expect_partial() while loading weights

# call summary on the object


# 1.2 Preprocessing
# Load the image
img = plt.imread("./task_1/Garden.jpg")
# Resize it into the size of 256x256. Use cv2 for this!

# Plot it!
#plt.title("Ground Truth")
#plt.imshow(img)
#plt.axis("off")
#plt.show()

# Remove the colors (average over all RGB values of a pixel)
#gray_img = 
# gray_img.shape = (256,256)

# Plot it!
#plt.title("Gray")
#plt.imshow(gray_img, cmap="gray")
#plt.axis("off")
#plt.show()

# Add color channel (gray)

# gray_img.shape = (256, 256, 1)

# Add batch dim

# gray_img.shape = (1, 256, 256, 1)


# Cast to tf.float32 by using tf.cast

# Normalization: [0,255] -> [-1, 1]

# 1.3 Inference
# Pass gray_img to the autoencoder
#ab_img = 

# Remove batch dim
#rgb_img = getRGB(gray_img, ab_img, batch_mode=False) # uncomment me!


#plt.title("Colorized")
#plt.imshow(rgb_img)
#plt.axis("off")
#plt.show()

## 2. Pairwise Concatenation

The tensor `x` represents a sequence of the following three elements: `[1,2,3]`, `[4,5,6]`, `[7,8,9]`.
<code>
tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)
</code>

Each element of the sequence shall be concatenated with each other - including with itself.
The result is the following tensor:
<code>
tf.Tensor: shape=(9, 6), dtype=int32, numpy=
array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [7, 8, 9, 1, 2, 3],
       [7, 8, 9, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]], dtype=int32
</code>

Write code that performs this operation with `x`.

In [28]:
x = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
seq_len = x.shape[0]
input_dim = x.shape[1]

# Hint: tile, concat and transpose is all you need ;)
# ... and a reshape 

## 3. Tensor Broadcasting 

Let `a` be a tensor with a shape of `(1,2,3)`.

Let `b` be a tensor with a shape of `(3,3)`.

Explain why the operation `a+b` can not be performed.

Your answer here